import { ROLES } from './roles.js';

export const PERMISSIONS = {
  // Asset Permissions
  CREATE_ASSET: 'CREATE_ASSET',
  UPDATE_ASSET: 'UPDATE_ASSET',
  DELETE_ASSET: 'DELETE_ASSET',
  ALLOCATE_ASSET: 'ALLOCATE_ASSET',
  
  // Transfers
  APPROVE_TRANSFER: 'APPROVE_TRANSFER',
  
  // Audits
  RUN_AUDIT: 'RUN_AUDIT',
  
  // Bookings
  BOOK_RESOURCE: 'BOOK_RESOURCE',
  
  // Maintenance
  APPROVE_MAINTENANCE: 'APPROVE_MAINTENANCE',
  
  // Users/Departments
  MANAGE_USERS: 'MANAGE_USERS',
  MANAGE_DEPARTMENTS: 'MANAGE_DEPARTMENTS'
};

export const ROLE_PERMISSIONS = {
  [ROLES.ADMIN]: [
    PERMISSIONS.CREATE_ASSET,
    PERMISSIONS.UPDATE_ASSET,
    PERMISSIONS.DELETE_ASSET,
    PERMISSIONS.ALLOCATE_ASSET,
    PERMISSIONS.APPROVE_TRANSFER,
    PERMISSIONS.RUN_AUDIT,
    PERMISSIONS.BOOK_RESOURCE,
    PERMISSIONS.APPROVE_MAINTENANCE,
    PERMISSIONS.MANAGE_USERS,
    PERMISSIONS.MANAGE_DEPARTMENTS
  ],
  [ROLES.ASSET_MANAGER]: [
    PERMISSIONS.CREATE_ASSET,
    PERMISSIONS.UPDATE_ASSET,
    PERMISSIONS.ALLOCATE_ASSET,
    PERMISSIONS.APPROVE_TRANSFER,
    PERMISSIONS.APPROVE_MAINTENANCE,
    PERMISSIONS.BOOK_RESOURCE,
    PERMISSIONS.RUN_AUDIT
  ],
  [ROLES.DEPARTMENT_HEAD]: [
    PERMISSIONS.APPROVE_TRANSFER,
    PERMISSIONS.BOOK_RESOURCE
  ],
  [ROLES.EMPLOYEE]: [
    PERMISSIONS.BOOK_RESOURCE
  ]
};
